
package org.asname.integration.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "calWebService", targetNamespace = "http://anil.hcl.com/", wsdlLocation = "file:/C:/Users/NEO/IdeaProjects/asname/core/src/main/java/org/asname/integration/ws/CalWebService.wsdl")
public class CalWebService_Service
    extends Service
{

    private final static URL CALWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALWEBSERVICE_EXCEPTION;
    private final static QName CALWEBSERVICE_QNAME = new QName("http://anil.hcl.com/", "calWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/NEO/IdeaProjects/asname/core/src/main/java/org/asname/integration/ws/CalWebService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALWEBSERVICE_WSDL_LOCATION = url;
        CALWEBSERVICE_EXCEPTION = e;
    }

    public CalWebService_Service() {
        super(__getWsdlLocation(), CALWEBSERVICE_QNAME);
    }

    public CalWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALWEBSERVICE_QNAME, features);
    }

    public CalWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, CALWEBSERVICE_QNAME);
    }

    public CalWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALWEBSERVICE_QNAME, features);
    }

    public CalWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalWebService
     */
    @WebEndpoint(name = "calWebServicePort")
    public CalWebService getCalWebServicePort() {
        return super.getPort(new QName("http://anil.hcl.com/", "calWebServicePort"), CalWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalWebService
     */
    @WebEndpoint(name = "calWebServicePort")
    public CalWebService getCalWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://anil.hcl.com/", "calWebServicePort"), CalWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALWEBSERVICE_EXCEPTION!= null) {
            throw CALWEBSERVICE_EXCEPTION;
        }
        return CALWEBSERVICE_WSDL_LOCATION;
    }

}
