
package org.asname.integration.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalWebService", targetNamespace = "http://anil.hcl.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalWebService {


    /**
     * 
     * @param addRq
     * @return
     *     returns org.asname.integration.ws.ResultType
     */
    @WebMethod(operationName = "Add")
    @WebResult(name = "AddRs", targetNamespace = "http://anil.hcl.com/", partName = "AddRs")
    public ResultType add(
        @WebParam(name = "AddRq", targetNamespace = "http://anil.hcl.com/", partName = "AddRq")
        AddRqType addRq);

    /**
     * 
     * @param diffRq
     * @return
     *     returns org.asname.integration.ws.ResultType
     */
    @WebMethod(operationName = "Diff")
    @WebResult(name = "DiffRs", targetNamespace = "http://anil.hcl.com/", partName = "DiffRs")
    public ResultType diff(
        @WebParam(name = "DiffRq", targetNamespace = "http://anil.hcl.com/", partName = "DiffRq")
        DiffRqType diffRq);

}
